export const RoleTypes = {
  ADMIN: "ORGANIZATION ADMIN",
  ADMIN_READ_ONLY: "ORGANIZATION READ ONLY",
  PROJECT_ADMIN: "PROJECT ADMIN",
  PROJECT_READ_ONLY: "PROJECT READ ONLY",
  INFRA_ADMIN: "INFRASTRUCTURE ADMIN",
  INFRA_READ_ONLY: "INFRASTRUCTURE READ ONLY",
  NAMESPACE_ADMIN: "NAMESPACE ADMIN",
  NAMESPACE_READ_ONLY: "NAMESPACE READ ONLY",
  CLUSTER_ADMIN: "CLUSTER ADMIN",
};
