export const AWS_REGIONS = [
  { label: "US East (N. Virginia)", value: "aws/us-east-1" },
  { label: "US East (Ohio)", value: "aws/us-east-2" },
  { label: "US West (N. California)", value: "aws/us-west-1" },
  { label: "US West (Oregon)", value: "aws/us-west-2" },
  { label: "Canada (Central)", value: "aws/ca-central-1" },
  { label: "EU (Frankfurt)", value: "aws/eu-central-1" },
  { label: "EU (Ireland)", value: "aws/eu-west-1" },
  { label: "EU (London)", value: "aws/eu-west-2" },
  { label: "EU (Milan)", value: "aws/eu-south-1" },
  { label: "EU (Paris)", value: "aws/eu-west-3" },
  { label: "EU (Stockholm)", value: "aws/eu-north-1" },
  { label: "Africa (Cape Town)", value: "aws/af-south-1" },
  { label: "Asia Pacific (Hong Kong)", value: "aws/ap-east-1" },
  { label: "Asia Pacific (Tokyo)", value: "aws/ap-northeast-1" },
  { label: "Asia Pacific (Seoul)", value: "aws/ap-northeast-2" },
  { label: "Asia Pacific (Osaka)", value: "aws/ap-northeast-3" },
  { label: "Asia Pacific (Singapore)", value: "aws/ap-southeast-1" },
  { label: "Asia Pacific (Sydney)", value: "aws/ap-southeast-2" },
  { label: "Asia Pacific (Mumbai)", value: "aws/ap-south-1" },
  { label: "South America (São Paulo)", value: "aws/sa-east-1" },
  { label: "Middle East (Bahrain)", value: "aws/me-south-1" },
];

export const AWS_EKS_REGIONS = [
  { label: "US East (N. Virginia)", value: "aws/us-east-1" },
  { label: "US East (Ohio)", value: "aws/us-east-2" },
  { label: "US West (Oregon)", value: "aws/us-west-2" },
  { label: "Canada (Central)", value: "aws/ca-central-1" },
  { label: "EU (Frankfurt)", value: "aws/eu-central-1" },
  { label: "EU (Ireland)", value: "aws/eu-west-1" },
  { label: "EU (London)", value: "aws/eu-west-2" },
  { label: "EU (Paris)", value: "aws/eu-west-3" },
  { label: "EU (Stockholm)", value: "aws/eu-north-1" },
  { label: "Asia Pacific (Hong Kong)", value: "aws/ap-east-1" },
  { label: "Asia Pacific (Tokyo)", value: "aws/ap-northeast-1" },
  { label: "Asia Pacific (Seoul)", value: "aws/ap-northeast-2" },
  { label: "Asia Pacific (Osaka)", value: "aws/ap-northeast-3" },
  { label: "Asia Pacific (Singapore)", value: "aws/ap-southeast-1" },
  { label: "Asia Pacific (Sydney)", value: "aws/ap-southeast-2" },
  { label: "Asia Pacific (Mumbai)", value: "aws/ap-south-1" },
  { label: "South America (São Paulo)", value: "aws/sa-east-1" },
  { label: "Middle East (Bahrain)", value: "aws/me-south-1" },
];

export const AWS_INSTANCE_TYPES_HA = [
  "m4.xlarge",
  "m4.2xlarge",
  "m4.4xlarge",
  "m4.10xlarge",
  "m4.16xlarge",
  "m5.xlarge",
  "m5.2xlarge",
  "m5.4xlarge",
  "m5.12xlarge",
  "m5.24xlarge",
  "m5a.xlarge",
  "m5a.2xlarge",
  "m5a.4xlarge",
  "m5a.12xlarge",
  "m5a.24xlarge",
  "m5ad.xlarge",
  "m5ad.2xlarge",
  "m5ad.4xlarge",
  "m5ad.12xlarge",
  "m5ad.24xlarge",
  "m5d.xlarge",
  "m5d.2xlarge",
  "m5d.4xlarge",
  "m5d.12xlarge",
  "m5d.24xlarge",
  "t2.xlarge",
  "t2.2xlarge",
  "t3.xlarge",
  "t3.2xlarge",
  "t3a.xlarge",
  "t3a.2xlarge",
  "i3.xlarge",
  "i3.2xlarge",
  "i3.4xlarge",
  "i3.8xlarge",
  "i3.16xlarge",
];

export const AWS_INSTANCE_TYPES_NON_HA = [
  "m4.2xlarge",
  "m4.4xlarge",
  "m4.10xlarge",
  "m4.16xlarge",
  "m5.2xlarge",
  "m5.4xlarge",
  "m5.12xlarge",
  "m5.24xlarge",
  "m5a.2xlarge",
  "m5a.4xlarge",
  "m5a.12xlarge",
  "m5a.24xlarge",
  "m5ad.2xlarge",
  "m5ad.4xlarge",
  "m5ad.12xlarge",
  "m5ad.24xlarge",
  "m5d.2xlarge",
  "m5d.4xlarge",
  "m5d.12xlarge",
  "m5d.24xlarge",
  "t2.2xlarge",
  "t3.2xlarge",
  "t3a.2xlarge",
  "i3.2xlarge",
  "i3.4xlarge",
  "i3.8xlarge",
  "i3.16xlarge",
];

export const AWS_INSTANCE_TYPES_GPU_HA = [
  "g3.4xlarge",
  "g3.8xlarge",
  "g3.16xlarge",
  "g3s.xlarge",
  "p2.xlarge",
  "p2.8xlarge",
  "p2.16xlarge",
  "p3.2xlarge",
  "p3.8xlarge",
  "p3.16xlarge",
];

export const AWS_INSTANCE_TYPES_GPU_NON_HA = [
  "g3.4xlarge",
  "g3.8xlarge",
  "g3.16xlarge",
  "g3s.xlarge",
  "p2.8xlarge",
  "p2.16xlarge",
  "p3.2xlarge",
  "p3.8xlarge",
  "p3.16xlarge",
];

export const GCP_REGIONS = [
  { label: "asia-east1 (Changhua County)", value: "gcp/asia-east1" },
  { label: "asia-east2 (Hong Kong)", value: "gcp/asia-east2" },
  { label: "asia-northeast1 (Tokyo)", value: "gcp/asia-northeast1" },
  { label: "asia-northeast2 (Osaka)", value: "gcp/asia-northeast2" },
  { label: "asia-south1 (Mumbai)", value: "gcp/asia-south1" },
  { label: "asia-southeast1 (Jurong West)", value: "gcp/asia-southeast1" },
  { label: "australia-southeast1 (Sydney)", value: "gcp/australia-southeast1" },
  { label: "europe-north1 (Hamina)", value: "gcp/europe-north1" },
  { label: "europe-west1 (St. Ghislain)", value: "gcp/europe-west1" },
  { label: "europe-west2 (London)", value: "gcp/europe-west2" },
  { label: "europe-west3 (Frankfurt)", value: "gcp/europe-west3" },
  { label: "europe-west4 (Eemshaven)", value: "gcp/europe-west4" },
  { label: "europe-west6 (Zürich)", value: "gcp/europe-west6" },
  {
    label: "northamerica-northeast1 (Montréal)",
    value: "gcp/northamerica-northeast1",
  },
  { label: "southamerica-east1 (Osasco)", value: "gcp/southamerica-east1" },
  { label: "us-central1 (Iowa)", value: "gcp/us-central1" },
  { label: "us-east1 (South Carolina)", value: "gcp/us-east1" },
  { label: "us-east4 (Northern Virginia)", value: "gcp/us-east4" },
  { label: "us-west1 (Oregon)", value: "gcp/us-west1" },
  { label: "us-west2 (California)", value: "gcp/us-west2" },
];

export const GCP_INSTANCE_TYPES_HA = [
  "n1-standard-4",
  "n1-standard-8",
  "n1-standard-16",
  "n1-standard-32",
  "n1-standard-64",
  "n1-standard-96",
  "n1-highmem-4",
  "n1-highmem-8",
  "n1-highmem-16",
  "n1-highmem-32",
  "n1-highmem-64",
  "n1-highmem-96",
  "n1-highcpu-4",
  "n1-highcpu-8",
  "n1-highcpu-16",
  "n1-highcpu-32",
  "n1-highcpu-64",
  "n1-highcpu-96",
  "n2-standard-4",
  "n2-standard-8",
  "n2-standard-16",
  "n2-standard-32",
  "n2-standard-48",
  "n2-standard-64",
  "n2-standard-80",
  "n2-highmem-4",
  "n2-highmem-8",
  "n2-highmem-16",
  "n2-highmem-32",
  "n2-highmem-48",
  "n2-highmem-64",
  "n2-highmem-80",
  "c2-standard-4",
  "c2-standard-8",
  "c2-standard-16",
  "c2-standard-30",
  "c2-standard-60",
];

export const GCP_INSTANCE_TYPES_NON_HA = [
  "n1-standard-8",
  "n1-standard-16",
  "n1-standard-32",
  "n1-standard-64",
  "n1-standard-96",
  "n1-highmem-8",
  "n1-highmem-16",
  "n1-highmem-32",
  "n1-highmem-64",
  "n1-highmem-96",
  "n1-highcpu-8",
  "n1-highcpu-16",
  "n1-highcpu-32",
  "n1-highcpu-64",
  "n1-highcpu-96",
  "n2-standard-8",
  "n2-standard-16",
  "n2-standard-32",
  "n2-standard-48",
  "n2-standard-64",
  "n2-standard-80",
  "n2-highmem-8",
  "n2-highmem-16",
  "n2-highmem-32",
  "n2-highmem-48",
  "n2-highmem-64",
  "n2-highmem-80",
  "c2-standard-8",
  "c2-standard-16",
  "c2-standard-30",
  "c2-standard-60",
];

export const GCP_INSTANCE_TYPES_GPU_HA = [""];

export const GCP_INSTANCE_TYPES_GPU_NON_HA = [""];

export const ClusterTypeLabels = {
  "on-prem": "On-prem",
  aws: "Amazon EC2",
  gcp: "Google Cloud Platform",
  "aws-eks": "Amazon EKS",
  gke: "Google Kubernetes Engine",
  aks: "Azure Kubernetes Service",
  import: "Import",
};
